"""Add doctor_availability table

Revision ID: af124211702f
Revises: 003_doctor_profiles
Create Date: 2026-10-03 05:31:48.917842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af124211702f'
down_revision: Union[str, None] = '003_doctor_profiles'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_availability',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name=op.f('ck_doctor_availability_ck_doctor_availability_day_of_week_range')),
    sa.CheckConstraint('slot_duration_minutes > 0', name=op.f('ck_doctor_availability_ck_doctor_availability_slot_duration_positive')),
    sa.CheckConstraint('start_time < end_time', name=op.f('ck_doctor_availability_ck_doctor_availability_time_order')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], name=op.f('fk_doctor_availability_doctor_id_doctor_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_availability'))
    )
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('doctor_profiles', 'consultation_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_doctor_profiles_doctor_code'), 'doctor_profiles', type_='unique')
    op.drop_constraint(op.f('uq_doctor_profiles_user_id'), 'doctor_profiles', type_='unique')
    op.drop_index(op.f('ix_doctor_profiles_doctor_code'), table_name='doctor_profiles')
    op.create_index(op.f('ix_doctor_profiles_doctor_code'), 'doctor_profiles', ['doctor_code'], unique=True)
    op.drop_index(op.f('ix_doctor_profiles_user_id'), table_name='doctor_profiles')
    op.create_index(op.f('ix_doctor_profiles_user_id'), 'doctor_profiles', ['user_id'], unique=True)
    op.drop_constraint(op.f('uq_patient_profiles_patient_code'), 'patient_profiles', type_='unique')
    op.drop_constraint(op.f('uq_patient_profiles_user_id'), 'patient_profiles', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_patient_profiles_user_id'), 'patient_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_patient_profiles_patient_code'), 'patient_profiles', ['patient_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_doctor_profiles_user_id'), table_name='doctor_profiles')
    op.create_index(op.f('ix_doctor_profiles_user_id'), 'doctor_profiles', ['user_id'], unique=False)
    op.drop_index(op.f('ix_doctor_profiles_doctor_code'), table_name='doctor_profiles')
    op.create_index(op.f('ix_doctor_profiles_doctor_code'), 'doctor_profiles', ['doctor_code'], unique=False)
    op.create_unique_constraint(op.f('uq_doctor_profiles_user_id'), 'doctor_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_doctor_profiles_doctor_code'), 'doctor_profiles', ['doctor_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('doctor_profiles', 'consultation_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_table('doctor_availability')
    # ### end Alembic commands ###
